name: Build

on:
  pull_request:
    branches:
      - 'trunk'

  push:
    branches:
      - 'trunk'
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: Swatinem/rust-cache@v2.2.0
      - uses: actions/checkout@v3
      
      - name: Update toolchain
        run: |
          rustup default stable-x86_64-pc-windows-msvc
          rustup update stable
          rustup toolchain add i686-pc-windows-msvc

      - name: Build and Package
        run: ./generate-release.ps1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: packaged-builds
          path: release/*

      - name: Upload & Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/all-x86_64.7z
            release/all-x86_64.7z.sha256
            release/all-i686.7z
            release/all-i686.7z.sha256
